#!/bin/env python

import argparse
from xai_visualization.train import train

if __name__ == "__main__":
    parser = argparse.ArgumentParser("start the training")
    parser.add_argument("--config", type=str, help="the config", required=False)
    args = parser.parse_args()

    config = Config()

    if args.config:
        config.load_json(args.config)
    else:
        config.load_constants()

    config.print()

    train()
