#!/bin/env python

import argparse
from xai_visualization.train import train
from xai_visualization.config import Config

if __name__ == "__main__":
    parser = argparse.ArgumentParser("start the training")
    parser.add_argument("--dataset", type=str, help="the path to the dataset", required=True)
    parser.add_argument("--model", type=str, help="the path to the model", required=True)
    parser.add_argument("--config", type=str, help="the config", required=False)
    args = parser.parse_args()

    config = Config()

    if args.config:
        config.load_json(args.config)
    else:
        config.load_defaults()

    config.print()

    train(config, args.dataset, args.model)
