#!/bin/env python

import argparse
from xai_visualization.config import Config
from xai_visualization.prepare.TFRecordsConverter import TFRecordsConverter
import numpy as np

if __name__ == "__main__":
    parser = argparse.ArgumentParser("convert input to tfrecords")
    parser.add_argument("--raw_data", type=str, help="the raw data", required=True)
    args = parser.parse_args()

    converter = TFRecordsConverter()
    converter.convert(args.raw_data, "./data/")
